[package]
name = "flatbuf_ping_pong"
version = "0.1.0"
authors = ["mmartinbar <maria@stampery.co>"]
build = "build.rs"

[dependencies]
flatbuffers = "0.4.0"

[build-dependencies]
#cc = "1.0"
#cmake = "0.1.34"
