#ifndef HANDSHAKE_VERIFIER_H
#define HANDSHAKE_VERIFIER_H

/* Generated by flatcc 0.5.3-pre FlatBuffers schema compiler for C by dvide.com */

#ifndef HANDSHAKE_READER_H
#include "handshake_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int Handshake_PingMessage_verify_table(flatcc_table_verifier_descriptor_t *td);
static int Handshake_PongMessage_verify_table(flatcc_table_verifier_descriptor_t *td);

static inline int Handshake_Version_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, Handshake_Version_identifier, 2, 1);
}

static inline int Handshake_Version_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, Handshake_Version_type_hash, 2, 1);
}

static inline int Handshake_Version_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 2, 1);
}

static inline int Handshake_Version_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 2, 1);
}

static int Handshake_PingMessage_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 1) /* version */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 8, 8) /* timestamp */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* message */)) return ret;
    return flatcc_verify_ok;
}

static inline int Handshake_PingMessage_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, Handshake_PingMessage_identifier, &Handshake_PingMessage_verify_table);
}

static inline int Handshake_PingMessage_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, Handshake_PingMessage_type_identifier, &Handshake_PingMessage_verify_table);
}

static inline int Handshake_PingMessage_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &Handshake_PingMessage_verify_table);
}

static inline int Handshake_PingMessage_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &Handshake_PingMessage_verify_table);
}

static int Handshake_PongMessage_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 1) /* version */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 8, 8) /* timestamp */)) return ret;
    return flatcc_verify_ok;
}

static inline int Handshake_PongMessage_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, Handshake_PongMessage_identifier, &Handshake_PongMessage_verify_table);
}

static inline int Handshake_PongMessage_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, Handshake_PongMessage_type_identifier, &Handshake_PongMessage_verify_table);
}

static inline int Handshake_PongMessage_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &Handshake_PongMessage_verify_table);
}

static inline int Handshake_PongMessage_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &Handshake_PongMessage_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* HANDSHAKE_VERIFIER_H */
